name: Release

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      target_release_tag:
        description: The tag of the release you want to append the artifact to
        required: true


jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache gradle files
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ./.gradle/loom-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle', 'gradle.properties', '**/*.accesswidener') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build
        env:
          BUILD_RELEASE: true

      - name: Upload to action artifact
        uses: actions/upload-artifact@v2
        with:
          name: 'build-artifacts'
          path: build/libs/

      - name: Get github release information
        if: ${{ github.event_name == 'workflow_dispatch' }}
        id: get_release
        uses: cardinalby/git-get-release-action@v1.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag: ${{ github.event.inputs.target_release_tag }}

      - name: Generate publish related infomation
        id: release_info
        run: |
          if [ $GITHUB_EVENT_NAME == 'release' ]
          then
              echo "::set-output name=tag_name::"  # leave an empty value here so softprops/action-gh-release will use the default value
          elif [ $GITHUB_EVENT_NAME == 'workflow_dispatch' ]
          then
              echo "::set-output name=tag_name::${{ github.event.inputs.target_release_tag }}"
          else
              echo Unknown github event name $GITHUB_EVENT_NAME
              exit 1
          fi

      - name: Read Properties mod_version
        id: mod_version
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: gradle.properties
          property: mod_version

      - name: Publish Minecraft Mods
        uses: Kir-Antipov/mc-publish@v2.1
        with:
          modrinth-id: FxyMyvSv
          modrinth-token: ${{ secrets.MODRINTH_API_TOKEN }}

          curseforge-id: 601770
          curseforge-token: ${{ secrets.CF_API_TOKEN }}

          github-tag: ${{ steps.release_info.outputs.tag_name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

          files-primary: build/libs/!(*-@(dev|sources)).jar
          files-secondary: ''

          name: ${{ format('MineStatistics v{0} universal', steps.mod_version.outputs.value) }}
          version: ${{ format('v{0}', steps.mod_version.outputs.value) }}
          version-type: release
          changelog: ${{ format('{0}{1}', github.event.release.body, steps.get_release.outputs.body) }}  # one of them should be an empty string (null)

          loaders: fabric
          game-versions: |
            1.14.4
            1.15.2
            1.16.5
            1.17.1
            1.18.2
          version-resolver: exact

          retry-attempts: 3
          retry-delay: 10000
